services:
  postgres:
    image: postgres:17-alpine
    container_name: android-shop-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: android_shop
      POSTGRES_USER: android_shop_user
      POSTGRES_PASSWORD: android_shop_password

    ports:
      - "5432:5432"

    volumes:
      - android_shop_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U android_shop_user -d android_shop"
        ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  android_shop_postgres_data: